-- V2__create_condicoes_climaticas.sql

-- Criação da tabela condicoes_climaticas
CREATE TABLE condicoes_climaticas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    condicao VARCHAR2(50) NOT NULL,
    temperatura NUMBER NOT NULL,
    umidade NUMBER NOT NULL,
    data_Hora TIMESTAMP NOT NULL,
    irradiacao_Solar NUMBER NOT NULL
);