-- V3__create_historico_recomendacoes.sql

-- Criação da tabela historico_recomendacoes
CREATE TABLE historico_recomendacoes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    recomendacao VARCHAR2(1000) NOT NULL,
    usuario_id NUMBER NOT NULL,
    condicao_climatica_id NUMBER NOT NULL,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios_global_java(id) ON DELETE CASCADE,
    CONSTRAINT fk_condicao_climatica FOREIGN KEY (condicao_climatica_id)
        REFERENCES condicoes_climaticas(id) ON DELETE CASCADE
);